FROM maven:3.8-eclipse-temurin-17-alpine AS build
WORKDIR /app

# Copy the source code
COPY server/src src
COPY server/pom.xml .
COPY server/google_checks.xml .

RUN apk add --no-cache sed
RUN sed -i 's/ls.host=localhost/ls.host=lobby-service/g' src/main/resources/application.properties
RUN sed -i 's/server.host=localhost/server.host=splendor-server/g' src/main/resources/application.properties

# Build the application
RUN mvn clean package -P prod -Dmaven.javadoc.skip=true

FROM eclipse-temurin:17-jre-alpine AS runtime
EXPOSE 4243

## Wait for LS to be ready
ENV WAIT_VERSION 2.7.2
ADD https://github.com/ufoscout/docker-compose-wait/releases/download/$WAIT_VERSION/wait /wait
RUN chmod +x /wait

COPY --from=build /app/target/server-0.0.1-SNAPSHOT.jar /app/splendor.jar
#ENTRYPOINT ["java","-jar","/app/splendor.jar"]

#Copy the json file
COPY ./server/src/main/resources/cards.json /app

# allow debug if startup fails, with: docker run -it --entrypoint /bin/bash splendor-server -s
RUN apk add --no-cache bash coreutils grep sed
