version: "3.8"
services:
  database:
    platform: linux/x86_64
    container_name: ls-db
    build:
      context: .
      dockerfile: Dockerfile-ls-db
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    ports:
      - "3453:3306"
  lobby-service:
    platform: linux/x86_64
    container_name: ls-api
    build:
      context: .
      dockerfile: Dockerfile-ls-api
    ports:
      - "4242:4242"
    depends_on:
      - database
    command: sh -c "/wait && java -jar /usr/app/ls.jar"
    environment:
      - WAIT_HOSTS=database:3306
      - WAIT_HOSTS_TIMEOUT=300
      - WAIT_SLEEP_INTERVAL=5
      - WAIT_HOST_CONNECT_TIMEOUT=5
  splendor-server:
    platform: linux/x86_64
    container_name: splendor-server
    profiles: ["with-server"]
    build:
      context: .
      dockerfile: Dockerfile-server
    ports:
      - "4243:4243"
    depends_on:
      - lobby-service
    command: sh -c "/wait && java -jar /app/splendor.jar"
    environment:
      - WAIT_HOSTS=lobby-service:4242
      - WAIT_HOSTS_TIMEOUT=300
      - WAIT_SLEEP_INTERVAL=5
      - WAIT_HOST_CONNECT_TIMEOUT=5
