# Action: https://github.com/marketplace/actions/publish-docker
name: Auto-Test and Publish Docker Server Image
on:
  pull_request:
    branches:
    - master
  push:
    branches:
    - master
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - uses: actions/checkout@v3
    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@v5
      with:
        name: comp361/f2022-hexanome-16/splendor-server
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        registry: ghcr.io
        dockerfile: Dockerfile-server
        cache: true
        tags: "${{ github.head_ref || github.ref_name }}"
